### PR TITLE
ensure expired in redis lock method

### PR DESCRIPTION
**Pull request by CoolElvis**

### CODE REVIEW

**Comment by gzigzigzeo** [comment]
Thanks!

**Comment by florrain** [comment]
@CoolElvis - Out of curiosity, could you tell what this fix is for and how the ensure block fixes it? Thanks

**Comment by CoolElvis** [comment]
@florrain -  If the redlock obtained  and exception occured before the ttl was set then next time the redlock cannot be obtained. Because the redlock will never released. 
We was catched  this kind of errors several times in production.

**Comment by gzigzigzeo** [comment]
@CoolElvis Just realized that probably .multi is the better option because if failure will happen during .ttl command lock will also never expire.

**Comment by CoolElvis** [comment]
I think may to try use  https://github.com/leandromoreira/redlock-rb

**Comment by gzigzigzeo** [comment]
@CoolElvis Well, to use separate library just for a single lock looks as an overkill, isn't it?

**Comment by CoolElvis** [comment]
@florrain , @gzigzigzeo  - Yes of course for this case  it is  overkill. But as advice for other projects you may pay attention to redlock-rb gem.
By the way, I created  https://github.com/CoolElvis/redlock_for_collection.

**Comment by CoolElvis** [comment]
@gzigzigzeo  What do you think about this?  : 
```ruby 
id = ns("lock:#{name}")
obtained = conn.set(id, true, nx: true, px: Sidekiq::Grouping::Config.lock_ttl)
````
instead of  
```ruby 
begin
  id = ns("lock:#{name}")
  obtained = conn.setnx(id, true)
ensure
  if obtained
    conn.expire(id, Sidekiq::Grouping::Config.lock_ttl)
  end
end
```

**Pull request merged**
