### PR TITLE
Add sidekiq versions to test against

### PR DESCRIPTION
**Pull request by antoshalee**

### CODE REVIEW

**Comment by sponomarev** [comment]
@antoshalee Unfortunately, there is no CI integration. Have you run all the tests locally against all the versions?

**Comment by gzigzigzeo** [comment]
@sponomarev Actually, integration is active, but there is no badge in README.

**Comment by sponomarev** [comment]
@gzigzigzeo Not only the badge 😉 

image

**Comment by antoshalee** [comment]
@sponomarev I have tested in my fork - it passed

**Comment by gzigzigzeo** [comment]
@sponomarev Strange, repo is active in travis. Will merge this now, and then will check.

**Pull request merged**
